import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.container}>
        <h1 className={styles.header}>Session Manager</h1>
        <button className={styles.startButton}>Get Started</button>
      </div>
    </div>
  );
};

export default Home;
